# TODO - create compose for api and add Dockerfile to generate and run production build
services:
  db:
    image: postgres:17
    container_name: postgres-advisor-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: advisordb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - advisor-network

volumes:
  db_data:

networks:
  advisor-network:
    driver: bridge
