services:
  db:
    image: postgres:17
    container_name: postgres-advisor-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: advisordb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - advisor-network

  api:
    build:
      context: .
    container_name: advisor-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/advisordb?schema=public"
      NODE_ENV: development
    depends_on:
      - db
    networks:
      - advisor-network

volumes:
  db_data:

networks:
  advisor-network:
    driver: bridge
